/**
 * Extended Database Types
 *
 * This file extends the auto-generated Supabase types with custom RPC functions
 * that are not automatically generated by `supabase gen types`.
 *
 * Pattern: Use MergeDeep from type-fest to safely extend generated types.
 * Reference: https://supabase.com/docs/guides/api/rest/generating-types
 *
 * To regenerate base types:
 * 1. npx supabase start
 * 2. npm run gen:types  (outputs to database-generated.types.ts)
 * 3. Update this file if new custom RPC functions are added
 */

import type { MergeDeep } from 'type-fest';
import type { Database as DatabaseGenerated, Json } from './database-generated.types';

// Re-export Json type from generated types
export type { Json } from './database-generated.types';

/**
 * Custom RPC function type definitions
 * Add new RPC functions here that are not auto-generated
 */
type CustomFunctions = {
  /**
   * Cursor-based pagination for admin event summary
   * RPC: get_admin_event_summary_cursor
   * Migration: 20251219000003_add_cursor_pagination_support.sql
   */
  get_admin_event_summary_cursor: {
    Args: {
      p_start_date?: string;
      p_end_date?: string;
      p_action_types?: string[];
      p_organization_id?: string;
      p_lot_number?: string;
      p_product_id?: string;
      p_include_recalled?: boolean;
      p_limit?: number;
      p_cursor_time?: string;
      p_cursor_key?: string;
    };
    Returns: {
      group_key: string;
      event_time: string;
      action_type: string;
      from_owner_type: string | null;
      from_owner_id: string | null;
      to_owner_type: string | null;
      to_owner_id: string | null;
      is_recall: boolean;
      recall_reason: string | null;
      total_quantity: number;
      lot_summaries: Json;
      sample_code_ids: string[];
      has_more: boolean;
    }[];
  };

  /**
   * Cursor-based pagination for history summary
   * RPC: get_history_summary_cursor
   * Migration: 20251219000003_add_cursor_pagination_support.sql
   */
  get_history_summary_cursor: {
    Args: {
      p_organization_id: string;
      p_action_types?: string[];
      p_start_date?: string;
      p_end_date?: string;
      p_is_recall?: boolean;
      p_limit?: number;
      p_cursor_time?: string;
      p_cursor_key?: string;
    };
    Returns: {
      group_key: string;
      action_type: string;
      from_owner_type: string | null;
      from_owner_id: string | null;
      from_owner_name: string | null;
      to_owner_type: string | null;
      to_owner_id: string | null;
      to_owner_name: string | null;
      is_recall: boolean;
      recall_reason: string | null;
      created_at: string;
      total_quantity: number;
      product_summaries: Json;
      has_more: boolean;
    }[];
  };

  /**
   * Cursor-based pagination for recalls
   * RPC: get_all_recalls_cursor
   * Migration: 20251219500006_add_get_all_recalls_cursor.sql
   */
  get_all_recalls_cursor: {
    Args: {
      p_start_date?: string;
      p_end_date?: string;
      p_type?: string;
      p_limit?: number;
      p_cursor_time?: string;
      p_cursor_key?: string;
    };
    Returns: {
      recall_id: string;
      recall_type: string;
      recall_date: string;
      recall_reason: string | null;
      quantity: number;
      from_org_id: string;
      from_org_name: string;
      from_org_type: string;
      to_id: string | null;
      to_name: string | null;
      to_type: string | null;
      product_summary: Json;
      code_ids: string[] | null;
      has_more: boolean;
    }[];
  };
};

/**
 * Extended Database type with custom RPC functions
 */
export type Database = MergeDeep<
  DatabaseGenerated,
  {
    public: {
      Functions: CustomFunctions;
    };
  }
>;

// Re-export utility types from generated file
export type {
  Tables,
  TablesInsert,
  TablesUpdate,
  Enums,
  CompositeTypes,
} from './database-generated.types';
